alias irbc="irb -r irb/completion"
alias lsh="ls -l --human-readable"
alias lss="du -sh"
alias cb=clipboard
alias unrare="unrar e -kb -o+"
alias rb="rhythmbox-client"
alias rbn="rb --next"
alias rbp="rb --previous"
alias mount.iso="mount -t iso9660 -o loop"
alias gs="git status"
alias e=editor
