#!/usr/bin/env ruby

unless ARGV[0]
  puts "usage: lines <format> [<file>]"
  exit -1
end

if ARGV[1]
  if matches = ARGV[0].match(/\/(.*)\//)
    print File.readlines(ARGV[1]).select {|x| x =~ Regexp.new(matches[1]) }.join("")
  else
  	if ARGV[0] == 'even'
  		i = 0
  		print File.open(ARGV[1]).readlines.select { (i += 1) % 2 == 0}.join("")
			exit 0
  	end
  	if ARGV[0] == 'odd'
  		i = 0
  		print File.open(ARGV[1]).readlines.select { (i += 1) % 2 != 0}.join("")
			exit 0
  	end
    IO.popen("sed -n '#{ARGV[0]}p' #{ARGV[1]}") do |f|
      print f.readlines.join("")
    end
  end
else
  if matches = ARGV[0].match(/\/(.*)\//)
    print STDIN.readlines.select {|x| x =~ Regexp.new(matches[1])}.join("")
  else
		if ARGV[0] == 'even'
			i = 0
			print STDIN.readlines.select { (i += 1) % 2 == 0}.join("")
			exit 0
		end
		if ARGV[0] == 'odd'
			i = 0
			print STDIN.readlines.select { (i += 1) % 2 != 0}.join("")
			exit 0
		end

    IO.popen("sed -n '#{ARGV[0]}p'") do |f|
      STDIN.readlines do |line|
        f.write line
      end
      print f.readlines.join("")
    end
  end
end

