#!/usr/bin/env ruby

require 'readline'

days = {
  "Mon" => "Pon",
  "Tue" => "Wto",
  "Wed" => "Śro",
  "Thu" => "Czw",
  "Fri" => "Pią",
  "Sat" => "Sob",
  "Sun" => "Nie"
}

if ARGV[0]
  line = ARGV[0]
else
  line = Readline.readline(": ")
end

date = Time.now.strftime("%Y-%m-%d %H:%M:%S")
line = date + ": " + line + "\n"
File.open("/home/wojtek/.log", "a") {|f| f.write line }
