#!/usr/bin/env ruby

def time_to_str(time)
	str = ""
	if time < 60
		time.to_s + "s"
	elsif time < 3600
		(time/60).to_s + "m " + (time%60).to_s + "s"
	elsif time < (3600 * 24)
		(time/3600).to_s + "h " + ((time%3600)/60).to_s + "m " + (time%60).to_s + "s"
	else
		(time/3600/24).to_s + "d " + ((time%(3600*24))/3600).to_s + "h " + ((time%3600)/60).to_s + "m " + (time%60).to_s + "s"
	end
end

time = 0
begin
	loop do
		STDOUT.write("\r"+" "*20)
		STDOUT.write("\r"+time_to_str(time))
		STDOUT.flush()
		sleep 1
		time = time + 1
	end
rescue Interrupt
end
puts
